### PR TITLE
SUBMARINE-68. Add tests to FileSystemOperations class

### PR DESCRIPTION
**Pull request by adamantal**
### What is this PR for?
Adding tests to `FileSystemOperations` class and also performed some minor refactor in the test infrastructure.

### What type of PR is it?
Refactoring

### Todos
* [ ] - new UTs should pass

### What is the Jira issue?
[SUBMARINE-68](https://issues.apache.org/jira/browse/SUBMARINE-68)

### How should this be tested?
* Only the new UTs should pass.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by adamantal** [comment]
@szilard-nemeth, the patch is rebased. Could you please take a look into this?

**Comment by adamantal** [comment]
Rebased to current master, will follow up on the UT errors.

**Comment by adamantal** [comment]
Fixing UT error, pushed again.

**Comment by yuanzac** [comment]
@adamantal,
LGTM
Thanks for the contributions.

**Comment by adamantal** [comment]
Thanks!

**Pull request closed without merging**
