### PR TITLE
SUBMARINE-74. Add tests to TensorFlowServiceSpec class

### PR DESCRIPTION
**Pull request by cchung100m**
### What is this PR for?

Add tests to TensorFlowServiceSpec class

### What type of PR is it?
[Improvement]

### Todos
* [ ] - Task

### What is the Jira issue?

https://issues.apache.org/jira/browse/SUBMARINE-74

### How should this be tested?

https://travis-ci.org/github/cchung100m/submarine?utm_medium=notification&utm_source=github_status

### Screenshots (if appropriate)

螢幕快照 2020-03-21 下午9 40 04

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by tangzhankun** [comment]
@cchung100m Thanks for the contribution. LGTM. One thing I'd like to add is that the yarn service runtime will be not our focus in the long term.

**Comment by cchung100m** [comment]
Hi @tangzhankun 

Understood, thanks for the review and comments. :)

**Comment by liuxunorg** [comment]
@cchung100m At present, the community does not plan to invest too much effort in developing yarn service, so you can adjust your work goals in future PRs.

**Comment by cchung100m** [comment]
@liuxunorg 

Thanks for suggestions. I would align the work with the community's target. :)

**Pull request closed without merging**
