### PR TITLE
SUBMARINE-768. Use code-generator to generate API

### PR DESCRIPTION
**Pull request by kevin85421**
#### Why submarine-cloud-v2?
* Because `submarine-cloud` is outdated, `submarine-cloud-v2` is the refactored version of `submarine-cloud`. In addition, after `submarine-cloud-v2` finishes, we will replace `submarine-cloud` with `submarine-cloud-v2`.
* More information is provided in SUBMARINE-760.

#### This PR
* Use code-generator to generate API.
* code-generator Github Repo: https://github.com/kubernetes/code-generator

### What type of PR is it?
[Feature]

### Todos
* Test the generated APIs
* Set Maven
* Define CRD

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-768

### How should this be tested?
* Refer to : https://github.com/kevin85421/hadoop-submarine/blob/SUBMARINE-768/submarine-cloud-v2/README.md

### Screenshots (if appropriate)
截圖 2021-03-16 下午5 28 22

https://user-images.githubusercontent.com/20109646/111286654-60eb4f00-867d-11eb-83bc-b7f7a1833179.mov

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? Yes
* Does this needs documentation? Yes

### CODE REVIEW

**Comment by kevin85421** [comment]
@pingsutw can you help me review this PR? I hope to move on as soon as possible.

**Review by pingsutw — COMMENTED** [review]
LGTM, Thanks @kevin85421 
cc @xunliu, Could you also take a look?

**Review by xunliu — COMMENTED** [review]
I have a question.

If I replace the `V1` folder with `V2`, I am not sure, whether the commit before `V1` will be emptied. If it will be emptied, we may have to create a `tag` to keep an old version, and then modify the code directly on `V1`.

@kevin85421 Can you test the above quest?

I think maybe we don't want to merge this PR for the time being, we need to discuss this issue.

**Comment by kevin85421** [comment]
@xunliu Thank you for your recommendation!

I have created a new branch `test` which deletes `submarine-cloud` directory.
[Link: test branch](https://github.com/kevin85421/hadoop-submarine/tree/test)

Next, I viewed the commit history of the `test` branch. The commits related to `submarine-cloud` still exist.
For instance, [SUBMARINE-316](https://github.com/kevin85421/hadoop-submarine/commits/test?after=49fabdaf77478c6f960e8d2de5abf0aab90cbc53+349&branch=test) still exists in the commit history of `test` branch.

Did I answer your question clearly?

**Review by xunliu — APPROVED** [review]
@kevin85421 Thank you for your contributions.
Good job!

**Comment by xunliu** [comment]
Will merge if no more comments.

**Pull request closed without merging**
