### PR TITLE
SUBMARINE-67. Add tests to Localizer class

### PR DESCRIPTION
**Pull request by adamantal**
### What is this PR for?
The goal is to add tests for the Localizer class. Also the class itself has been refactored a bit (methods from `handleLocalizations` have been decoupled).

### What type of PR is it?
Refactoring | Test

### Todos
No TODOs.

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-67

### How should this be tested?
* No integration tests is needed.
* The new unit tests should pass.

### Screenshots (if appropriate)
Not needed.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by liuxunorg** [comment]
hi, @adamantal 
Thank you contribute this PR.
Please read the PR specification first: https://github.com/apache/hadoop-submarine/blob/master/docs/community/contributing.md#creating-a-pull-request

So, Please change 

### What is the Jira issue?
[SUBMARINE-67]

to

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-67

**Comment by adamantal** [comment]
Thanks for checking the patch @jiwq, renamed `TestLocalizer` to `LocalizerTest`.
I was unaware that Submarine has a pretty good Contributing guide (that also included the reference for the style guide), checked that too.

If you have any concerns regarding the patch please let me know.

**Comment by yuanzac** [comment]
@adamantal, Thanks for your contribution.
The test failed. Can you take a look?

**Comment by adamantal** [comment]
Yeah sure, @yuanzac.

I saw two problems: I forgot to amend my last commit and the new line checks were failing (the file did not end newline). Fixed both & force pushed.

**Comment by adamantal** [comment]
Build failed with hadoop-3.1 and hadoop-3.2 profiles due to some conflicting imports. Removed the unnecessary ones. The build was successful with both profiles on my local. 

Pending on jenkins.

**Comment by jiwq** [comment]
+1

**Comment by yuanzac** [comment]
Thanks, @adamantal for your contribution.
Thanks @liuxunorg and @jiwq for your review. 
I'll merge this PR shortly.

**Comment by adamantal** [comment]
Thanks for the review and commit @jiwq and @yuanzac !

**Pull request closed without merging**
