### PR TITLE
SUBMARINE-774. Support parsing conda config file

### PR DESCRIPTION
**Pull request by KUAN-HSUN-LI**
### What is this PR for?
1. Improve the UI, created in #534 
2. Parse the uploaded conda config file
3. Enable the updated API in #540 
4. remove the kernelSpec block
### What type of PR is it?
[Improvement]

### Todos
- [ ] (test the parsing function)

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-785

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? Yes
* Does this needs documentation? No

### CODE REVIEW

**Review by xunliu — COMMENTED** [review]
@KUAN-HSUN-LI Please trigger travis CI again.
I see that the previous ci is failed.

**Comment by jojochuang** [comment]
restarting the job: https://travis-ci.com/github/apache/submarine/jobs/497217209

**Comment by KUAN-HSUN-LI** [comment]
Sorry, I missed updating the E2E test.
I will fix it soon.

**Review by xunliu — APPROVED** [review]
@KUAN-HSUN-LI Thank you for your contributions.
Will merge if no more comments.

**Pull request closed without merging**
