### PR TITLE
SUBMARINE-1111. Add description of creating yaml files for custom resources.

### PR DESCRIPTION
**Pull request by FYRichie**
…ource.

### What is this PR for?
Update developer-guide.md in submarine cloud v2.
The update includes notifications of not using helm and other tips.

### What type of PR is it?
Improvement

### Todos
None

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-1111

### How should this be tested?
None
### Screenshots (if appropriate)
None
### Questions:
* Do the license files need updating? No
* Are there breaking changes for older versions? No
* Does this need new documentation? No

### CODE REVIEW

**Comment by KUAN-HSUN-LI** [comment]
@FYRichie  You need to fix the tests.

**Comment by FYRichie** [comment]
@KUAN-HSUN-LI , I just realized that there are several files that came up from nowhere, and I believe that's the reason to failed the test. I've just simply removed them, is it a valid solution?

**Review by KUAN-HSUN-LI — COMMENTED** [review]
Also, remove the $etc *$ file?

**Review by KUAN-HSUN-LI — APPROVED** [review]
+1

**Pull request closed without merging**
