### PR TITLE
SUBMARINE-669. Notebook name contain only lowercase alphanumeric characters or '-'

### PR DESCRIPTION
**Pull request by charlie0220**
### What is this PR for?
Fix the rule of "Notebook Name" while creating new notebook and add description in userdocs.
Now notebook name should follow the DNS label standard as defined in RFC 1123.
1. Contain at most 63 characters.
2. Contain only lowercase alphanumeric characters or '-'.
3. Start with an alphanumeric character.
4. End with an alphanumeric character.

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
[SUBMARINE-669](https://issues.apache.org/jira/projects/SUBMARINE/issues/SUBMARINE-669?filter=allopenissues)

### How should this be tested?
[Travis CI](https://travis-ci.com/github/charlie0220/submarine/builds/199579036)

### Screenshots (if appropriate)
screen-capture

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by lowc1012** [comment]
@charlie0220 Thanks for your contribution!
@kobe860219 Could you please help me review this PR ?

**Review by kobe860219 — APPROVED** [review]
@charlie0220 Thanks for your contribution! LGTM 👍

**Comment by lowc1012** [comment]
@charlie0220 @kobe860219 
Would it be better if we display validation message under the input field?

**Comment by kobe860219** [comment]
@lowc1012 @charlie0220  I will embed ng-zorro to notebook page soon!

**Review by pingsutw — APPROVED** [review]
+1

**Comment by charlie0220** [comment]
I found out a problem. Please do not merge this PR.

**Review by lowc1012 — APPROVED** [review]
+1. Thanks @charlie0220

**Review by xunliu — COMMENTED** [review]
@charlie0220 Will merge If no more comments.

**Review by pingsutw — APPROVED** [review]
Thanks @charlie0220 for your contribution

**Pull request closed without merging**
