### PR TITLE
SUBMARINE-807. Create a tensorboard for a single user

### PR DESCRIPTION
**Pull request by Kenchu123**
### What is this PR for?

Create a submarine tensorboard for a single user via the submarine operator.

Reference: https://github.com/apache/submarine/blob/master/helm-charts/submarine/templates/submarine-tensorboard.yaml

### What type of PR is it?
[Feature]

### What is the Jira issue?

https://issues.apache.org/jira/projects/SUBMARINE/issues/SUBMARINE-807

### How should this be tested?

```
# initialization
# Step1: Register Custom Resource Definition
kubectl apply -f artifacts/examples/crd.yaml

# Step2: Create a Custom Resource
kubectl apply -f artifacts/examples/example-submarine.yaml

# in-cluster
cd submarine/submarine-cloud-v2
eval $(minikube docker-env)
make image
kubectl apply -f artifacts/examples/submarine-operator-service-account.yaml
kubectl apply -f artifacts/examples/submarine-operator.yaml

# out-of-cluster
go build -o submarine-operator
./submarine-operator

# helm
cd submarine
helm install submarine ./helm-charts/submarine

```

### Screenshots (if appropriate)

+ PersistentVolume (helm)

helm-pv

+ PersistentVolume (operator)

**Note**: PersistentVolumes are not namespaced resources, so we add the namespace as a suffix to distinguish them

operator-pv

+ PersistentVolumeClaim (helm)

helm-pvc

+ PersistentVolumeClaim (operator)

operator-pvc

+ Deployment (helm)

helm-deployment

+ Deployment (operator)

operator-deployment

+ Service (helm)

helm-service

+ Service (opertator)

operator-service

+ IngressRoute (helm)

helm-ingressroute

+ IngressRoute (operator)

operator-ingressroute

+ Workbench

[Video](https://imgur.com/9Wk8Rnh)

### Questions:

* Do the license files need updating? No
* Are there breaking changes for older versions? No
* Does this need new documentation? No

### CODE REVIEW

**Comment by kevin85421** [comment]
@MortalHappiness Can you help Ken review this PR?

**Comment by MortalHappiness** [comment]
LGTM

**Review by MortalHappiness — APPROVED** [review]
LGTM

**Review by xunliu — APPROVED** [review]
@Kenchu123 Thanks you for your contributions.
LGTM
Will merge if no more comments.

**Pull request closed without merging**
