### PR TITLE
SUBMARINE-808. Temporarily remove hitcount badge because the server is broken

### PR DESCRIPTION
**Pull request by ByronHsu**
### What is this PR for?
The hitcount server is shut down for an unknown reason. (https://hits.dwyl.com/)
Temporarily remove it until the server is up again.

### What type of PR is it?
[Bug Fix]

### CODE REVIEW

**Review by kevin85421 — APPROVED** [review]
+1

**Review by xunliu — APPROVED** [review]
LGTM

**Comment by xunliu** [comment]
@ByronHsu Please fixed conflicts, Thanks.

**Comment by ByronHsu** [comment]
@kevin85421 The Pypl badger is broken too. Have no idea...

**Comment by xunliu** [comment]
Will merge if no more comments.

**Pull request closed without merging**
