### PR TITLE
SUBMARINE-1081. Upgrade helm-charts crd version to v1

### PR DESCRIPTION
**Pull request by chiaoymir**
### What is this PR for?

Now, we are using old v1beta1 api version for our crd. We want to replace it with the new v1 version to support higher versions of kubernetes.

### What type of PR is it?
[Improvement]

### Todos
* [x] - Upgrade some role-binding version, cluster-role-binding, and ingress version
* [x] - Upgrade pytorchjob, tfjob, traefik to v1

### What is the Jira issue?

https://issues.apache.org/jira/projects/SUBMARINE/issues/SUBMARINE-1081?filter=allissues

### Questions:
* Do the license files need updating? No
* Are there breaking changes for older versions? No
* Does this need new documentation? No

### CODE REVIEW

**Comment by woodcutter-eric** [comment]
This PR is experimental. Confronted with some difficulties now.

**Comment by cdmikechen** [comment]
@chiaoymir 
How's the PR going now? Hope the relevant CRDs can be upgraded to the latest version.

**Comment by cdmikechen** [comment]
@chiaoymir 
Hi~ What is the current status of the PR, please? 
If there are no updates to this PR, I may consider closing this PR and reworking the new helm deployment and server resources based on the master branch.

**Comment by chiaoymir** [comment]
I no longer update this PR. You can close it and rework a new one.

**Comment by cdmikechen** [comment]
@chiaoymir 
Thank you for your reply. I'will close this PR. When a new PR is created I will also let you know about details of the new change.

**Pull request closed without merging**
