### PR TITLE
SUBMARINE-904. Create minio by submarine operator for single user

### PR DESCRIPTION
**Pull request by Kenchu123**
### What is this PR for?

Create minio by submarine operator for single user

### What type of PR is it?
[Feature]

### What is the Jira issue?

https://issues.apache.org/jira/browse/SUBMARINE-904
### Screenshots (if appropriate)

https://user-images.githubusercontent.com/17617373/124442678-909aa000-ddaf-11eb-93a8-6a3551ab0889.mov

### Questions:
* Do the license files need updating? No
* Are there breaking changes for older versions? No
* Does this need new documentation? 

No

### CODE REVIEW

**Comment by Kenchu123** [comment]
@MortalHappiness @kevin85421 I have finished adding minio by operator, pls help me review!

**Comment by MortalHappiness** [comment]
@Kenchu123 You changed `types.go` but forgot to run `make api`.

**Comment by Kenchu123** [comment]
@MortalHappiness  I have run `make api` and made the change.

**Comment by MortalHappiness** [comment]
LGTM

**Review by kevin85421 — APPROVED** [review]

**Review by kevin85421 — CHANGES_REQUESTED** [review]
@Kenchu123 Let me know if you resolve the conflict.

**Comment by Kenchu123** [comment]
@kevin85421  I have resolved the conflict.

**Review by kevin85421 — APPROVED** [review]
LGTM

**Pull request closed without merging**
