### PR TITLE
SUBMARINE-935. Support test-k8s on both KinD and minikube

### PR DESCRIPTION
**Pull request by KUAN-HSUN-LI**
### What is this PR for?
Support running the test-k8s on both KinD and minikube
image

### What type of PR is it?
[Improvement]

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-935

### How should this be tested?
KinD is tested in CI.
minikube should be tested following the document

### Questions:
* Do the license files need updating? No
* Are there breaking changes for older versions? No
* Does this need new documentation? No

### CODE REVIEW

**Comment by KUAN-HSUN-LI** [comment]
@kevin85421 Can you help me review this PR. Thanks in advance!

**Review by kevin85421 — COMMENTED** [review]
It looks good to me. Can you add a screenshot about running test-k8s with minikube? In addition, add a hyperlink to [IntegrationTestK8s.md](https://github.com/apache/submarine/blob/master/website/docs/devDocs/IntegrationTestK8s.md).

**Comment by KUAN-HSUN-LI** [comment]
@kevin85421 Thanks for your review.
I add a result image of passing the test-k8s with minikube, but I am not sure whether this image is clear enough.

**Review by kevin85421 — APPROVED** [review]
LGTM

**Pull request closed without merging**
