### PR TITLE
SUBMARINE-973. Versioning website

### PR DESCRIPTION
**Pull request by KUAN-HSUN-LI**
### What is this PR for?
1. Create version control on submarine website
2. Change the image relative path into absolute path. (reduce the old version doc folder size from 10MB to 500KB)
3. Beautify the Submarine home page
4. Create the submarine favicon

### What type of PR is it?
[Improvement | Documentation]

### Todos
* [ ] - Wait until v0.6.0 is released

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-973

### Screenshots (if appropriate)

https://user-images.githubusercontent.com/38066413/129465200-b9d0987f-423a-4b14-9850-613d69ebc6d4.mp4

螢幕擷取畫面 2021-08-15 104242

### Questions:
* Do the license files need updating? No
* Are there breaking changes for older versions? No
* Does this need new documentation? No

### CODE REVIEW

**Review by pingsutw — APPROVED** [review]
Thank you for improving documentation, it's great to have different versions of docs.
Overall LGTM

**Comment by pingsutw** [comment]
@KUAN-HSUN-LI Could you fix the conflict? I'm going to merge it.

**Comment by KUAN-HSUN-LI** [comment]
@pingsutw I have sync the current doc to the version-0.6.0 doc and fix one error however the `Release Note` page is not ready. Thanks for your review.

**Comment by pingsutw** [comment]
Got it, Thnaks~

**Pull request closed without merging**
