### PR TITLE
SUBMARINE-399. Support Hadoop 2.10

### PR DESCRIPTION
**Pull request by jojochuang**
### What is this PR for?
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - https://submarine.apache.org/contribution/contributions.html

### What type of PR is it?
Feature

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-399

### How should this be tested?
https://travis-ci.org/jojochuang/hadoop-submarine/builds/657551872

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? Yes

### CODE REVIEW

**Comment by yuanzac** [comment]
Thanks @jojochuang,
LGTM, but there are some conflicts. Can you take a look?

**Comment by jojochuang** [comment]
This build passed tests: https://travis-ci.org/jojochuang/hadoop-submarine/builds/657906999?utm_medium=notification&utm_source=email

**Comment by pingsutw** [comment]
+1, Thanks @jojochuang. LGTM

**Comment by liuxunorg** [comment]
@jojochuang Thank you for this contribution.
I have a question, Can this PR solve this [ISSUE-198. restart hadoop services occurred an error when I finished the GPU setting for RM、NM and container-executor.cfg](https://github.com/apache/submarine/issues/198) problem?

**Comment by jojochuang** [comment]
> @jojochuang Thank you for this contribution.
> I have a question, Can this PR solve this [ISSUE-198. restart hadoop services occurred an error when I finished the GPU setting for RM、NM and container-executor.cfg](https://github.com/apache/submarine/issues/198) problem?

I think that's a separate issue. I did not encounter that problem during test.

**Pull request closed without merging**
