### PR TITLE
SUBMARINE-1275. Submarine-cloud-v3 reconcile logic

### PR DESCRIPTION
**Pull request by joshvictor1024**
### What is this PR for?
Add reconcile logic to submarine-cloud-v3

### What type of PR is it?
Feature

### Todos
* [x] - add reconcile logic
* [x] - update cluster role rules
* [x] - add new development doc

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-1275

### How should this be tested?
Follow the `submarine-cloud-v3/docs/developer-guide.md`

### Screenshots (if appropriate)
SUBMARINE-1275

### Questions:
* Do the license files need updating? No
* Are there breaking changes for older versions? Yes
* Does this need new documentation? Yes

### CODE REVIEW

**Comment by joshvictor1024** [comment]
Please help review @Kenchu123 @MortalHappiness , thanks.

**Comment by cdmikechen** [comment]
Do we need to add some k8s labels like `app.kubernetes.io/name=submarine`?
I think we may need to add some labels to these k8s resources. This is convenient for users to filter resources based on labels.
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**Comment by joshvictor1024** [comment]
@cdmikechen Right now, the labels created with `submarine-cloud-v3` match those created with `submarine-cloud-v2`. 

I think convenience is outside the scope of this PR. We could add that label along with others such as `app.kubernetes.io/created-by=controller-runtime` in a separate PR for easy reviewing. Also, if I understand the guide you provided correctly, should the label `app.kubernetes.io/name=submarine` also be applied to the resources created by Helm, like `deployment.apps/training-operator`? In that case, I think those are again outside the scope of this PR.

**Comment by MortalHappiness** [comment]
I also think we can create another issue for adding the label.

**Comment by MortalHappiness** [comment]
I created an issue for adding labels. I will merge this PR first before dealing with that issue.

https://issues.apache.org/jira/browse/SUBMARINE-1290

**Pull request closed without merging**
