### PR TITLE
SUBMARINE-520. Bump Tony to 0.3.25

### PR DESCRIPTION
**Pull request by pingsutw**
### What is this PR for?
Update Tony version to 0.3.25

### What type of PR is it?
[Improvement]

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-520
### How should this be tested?
https://travis-ci.org/github/pingsutw/hadoop-submarine/builds/692855197

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by tangzhankun** [comment]
@pingsutw , any TonY new features in this version that we required?

**Comment by liuxunorg** [comment]
If there is no problem with submarine's `Tony` now, I suggest not to update it in the future.

**Comment by pingsutw** [comment]
Thanks for the review
https://github.com/linkedin/TonY/commit/4c9a26bddbad67ed561c0cce8dba3988cd47830d
https://github.com/linkedin/TonY/commit/58b56ec13bb2ba19d824f09243eee2a1e537bba7
https://github.com/linkedin/TonY/commit/673efee71d9818c70270d3525f3555a43bbfd75a
@yuanzac and I had fix some issues related to submarine in v0.3.25
These commits were in the Tony submodule before.

v0.3.25 also fixes some issues related to the submarine.
https://github.com/linkedin/TonY/releases

**Comment by liuxunorg** [comment]
Will merge if no more comments.

**Pull request closed without merging**
