### PR TITLE
SUBMARINE-1292. Add submarine-cloud-v3 e2e test

### PR DESCRIPTION
**Pull request by joshvictor1024**
### What is this PR for?

Add end-to-end test to submarine-cloud-v3

### What type of PR is it?
Feature

### Todos
* [x] - prepare to run in-cluster
* [x] - write e2e test and add to Github Action
* [x] - add new development doc

### What is the Jira issue?

https://issues.apache.org/jira/browse/SUBMARINE-1292

### How should this be tested?

Follow `submarine-cloud-v3/docs/developer-guide.md`

### Questions:

* Do the license files need updating? No
* Are there breaking changes for older versions? No
* Does this need new documentation? Yes

### CODE REVIEW

**Comment by cdmikechen** [comment]
hi, @joshvictor1024
Maybe we can change PR title to SUBMARINE-1292. Add submarine-cloud-v3 e2e test ?

**Comment by cdmikechen** [comment]
```dockerfile
# manager is run as non-root user
# See submarine-cloud-v3/config/manager/manager.yaml
RUN addgroup -g 1000 -S mygroup
RUN adduser -u 1000 -S myuser -G mygroup
USER myuser
```
I think we can change `mygroup` and `myuser` to `submarine`

**Comment by joshvictor1024** [comment]
> Hi, @joshvictor1024 thank you for your contribution~ Maybe we can change PR title to [SUBMARINE-1292](https://issues.apache.org/jira/browse/SUBMARINE-1292). Add submarine-cloud-v3 e2e test ?

Sorry, forgot about title format. Fixed.

> ```dockerfile
> # manager is run as non-root user
> # See submarine-cloud-v3/config/manager/manager.yaml
> RUN addgroup -g 1000 -S mygroup
> RUN adduser -u 1000 -S myuser -G mygroup
> USER myuser
> ```
> 
> I think we can change `mygroup` and `myuser` to `submarine`

Good point, thanks.

**Review by MortalHappiness — APPROVED** [review]
LGTM

**Pull request closed without merging**
