### PR TITLE
SUBMARINE-554. [WEB] UI for Submarine experiment creation

### PR DESCRIPTION
**Pull request by wang0630**
### What is this PR for?
Renew UI for experiment creation.

### What type of PR is it?
[Improvement]

### Todos
* [ ] - Task

### What is the Jira issue?
[SUBMARINE-554](https://issues.apache.org/jira/browse/SUBMARINE-554)

### How should this be tested?
https://travis-ci.com/github/wang0630/submarine/builds/174373510

### Screenshots (if appropriate)
new

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by pingsutw** [comment]
WIP

**Comment by liuxunorg** [comment]
@wang0630 Please change PR title to `SUBMARINE-554. xxxxx`
Please view https://github.com/apache/submarine/blob/master/docs/community/contributing.md#creating-a-pull-request
```
### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/SUBMARINE/
* Put link here, and add [SUBMARINE-${jira_number}] in PR title, e.g. [SUBMARINE-323]
```

**Comment by pingsutw** [comment]
@liuxunorg The test failure is related to the PR.
@wang0630 is going to fix it.

**Comment by liuxunorg** [comment]
> @liuxunorg The test failure is related to the PR.
> @wang0630 is going to fix it.

OK

**Comment by wang0630** [comment]
Tests have been added and ready for merge.

**Comment by pingsutw** [comment]
Thansk @wang0630 
will merge if no more comment.

**Pull request closed without merging**
