### PR TITLE
SUBMARINE-592. ExperimentRestApiIT#testTensorFlowUsingEnvWithJsonSpec assert fixes

### PR DESCRIPTION
**Pull request by manirajv06**
### What is this PR for?
https://issues.apache.org/jira/browse/SUBMARINE-592

### What type of PR is it?
Bug Fix

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-592

### How should this be tested?
* First time? Setup Travis CI as described on https://submarine.apache.org/contribution/contributions.html#continuous-integration
* Strongly recommended: add automated unit tests for any new or changed behavior
* Outline any manual steps to test the PR here.

### Questions:
* Does the licenses files need update? Yes/No
* Is there breaking changes for older versions? Yes/No
* Does this needs documentation? Yes/No

### CODE REVIEW

**Comment by manirajv06** [comment]
@pingsutw Can you please take a look? 
Also, a general question of Git PR work flow - This PR should contain only https://github.com/apache/submarine/pull/370/commits/b9c5475ec3eb019a68f143650ddcadece098d5ef, but it is showing up PR commits as well which is not yet reviewed and committed by Reviewers. In this case, Should I need to squash those un necessary commits before committing the code for this PR or Would reviewers take care of this?

**Comment by liuxunorg** [comment]
@manirajv06 Thank you contribution.
The title of this PR is too long, please shorten it.

**Comment by manirajv06** [comment]
> The PR should only contain the commit related to this Jira, or other commits will also be merged.
> After dropping out the other commits and force push again, we could merge this PR.

done

**Comment by manirajv06** [comment]
> @manirajv06 Thank you contribution.
> The title of this PR is too long, please shorten it.

done

**Pull request closed without merging**
