### PR TITLE
SUBMARINE-49 Add more test coverage to RunJobParameters

### PR DESCRIPTION
**Pull request by adamantal**
### What is this PR for?
For easier maintainability decoupled some parameter-related responsibilities to separates classes and added unit tests for them.

### What type of PR is it?
Refactoring

### Todos
* [ ] - UTs should pass

### What is the Jira issue?
* [SUBMARINE-49](https://issues.apache.org/jira/browse/SUBMARINE-49)

### How should this be tested?
* No further testing is needed.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by jiwq** [comment]
@adamantal Thanks for your contribution. But I'm sorry to tell you that the submarine-client will be refactored after the submarine-server finished, the submarine-client submit the job through REST/RPC, then the submarine-client no longer depend on hadoop. So I think we'd better ignore the submarine-client related works until the server finished. If you are interested in server, welcome to contributes.

**Comment by liuxunorg** [comment]
@adamantal Thanks for your contribution. :-)
Yes, the community has plans to adjust the design of the client module.
But before adjustment, I think we can still optimize according to the current client architecture, such as adding test cases, However, the new features of the client module are no longer accepted.
@jiwq @tangzhankun @yuanzac  What do you guys think?

**Comment by jiwq** [comment]
> @adamantal Thanks for your contribution. :-)
> Yes, the community has plans to adjust the design of the client module.
> But before adjustment, I think we can still optimize according to the current client architecture, such as adding test cases, However, the new features of the client module are no longer accepted.
> @jiwq @tangzhankun @yuanzac What do you guys think?

+1 Agree for the suggestion. 

@adamantal Can you help to check the UT failed reason and fix it?

**Comment by adamantal** [comment]
Hi @jiwq, @liuxunorg.

Thanks for explanation. I will refrain myself from working on submarine-client related features in the near future.

However it wasn't clear to me what to do with this PR. I'm not making new feature in this, just separated the parameters by responsibility - with the purpose of unit testing. The patch mainly concerns submarine-client, the submarine-server related changes are just the consequence of that, so I cannot really get rid of the submarine-client part of the change.
How should I proceed?

**Comment by jiwq** [comment]
Hi @adamantal , I think this PR can be closed because it costs some time to refactor, except that someone can help to review.

**Pull request closed without merging**
