### PR TITLE
SUBMARINE-412. Basic GitHub aciton support for submarine project

### PR DESCRIPTION
**Pull request by yaooqinn**
### What is this PR for?

Add build/rat/linter GitHub actions for a fast check to help developers to fix trivial things

### What type of PR is it?
Improvement
### Todos
* [ ] - rm same logic in travis untils this is stable

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-412

### How should this be tested?

GitHub action triggered

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by yaooqinn** [comment]
oops.. seems only Only repository collaborators can create workflows.

**Comment by pingsutw** [comment]
@yaooqinn Thanks for working on it.
We need to create a JIRA ticket. more info could refer to this [guide](https://github.com/apache/submarine/blob/master/docs/community/contributing.md)
submarine jira: https://issues.apache.org/jira/projects/SUBMARINE/issues/

**Comment by yaooqinn** [comment]
thanks @pingsutw

**Comment by liuxunorg** [comment]
@yaooqinn Thank you for contribution this feature.
Will merge if no more comments.

**Pull request closed without merging**
