### PR TITLE
SUBMARINE-900. Create a submarine mlflow for single user

### PR DESCRIPTION
**Pull request by Kenchu123**
### What is this PR for?

Create  a submarine mlflow by operator for single user.

### What type of PR is it?

[Feature]

### What is the Jira issue?

https://issues.apache.org/jira/browse/SUBMARINE-900

### Screenshots (if appropriate)

https://user-images.githubusercontent.com/17617373/124424951-72767500-dd9a-11eb-8e4c-db21ea8d56c6.mov

### Questions:
* Do the license files need updating? No
* Are there breaking changes for older versions? No
* Does this need new documentation? No

### CODE REVIEW

**Comment by Kenchu123** [comment]
@kevin85421  @MortalHappiness I have finished creating mlflow by operator, pls help me review !

**Comment by MortalHappiness** [comment]
@Kenchu123 Did you run `gofmt` on these files?

**Comment by Kenchu123** [comment]
@MortalHappiness  I have fixed the bug. It may be my editor's tab indent not set right.

**Comment by MortalHappiness** [comment]
LGTM

**Review by kevin85421 — APPROVED** [review]

**Pull request closed without merging**
