### PR TITLE
SUBMARINE-695. Doesn't allocate GPU resource while creating notebook

### PR DESCRIPTION
**Pull request by kobe860219**
### What is this PR for?
Modify resources spec when create new notebook. Fix the problem doesn't allocate GPU resource while creating notebook.

### What type of PR is it?
[Bug Fix]

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-695

### How should this be tested?
https://travis-ci.org/github/kobe860219/submarine/builds/749244070

### Questions:
* Does the licenses files need update? 
* Is there breaking changes for older versions? 
* Does this needs documentation?

### CODE REVIEW

**Comment by kobe860219** [comment]
@lowc1012  Please help me review, thanks!

**Review by lowc1012 — APPROVED** [review]
LGTM, Thanks @kobe860219

**Comment by lowc1012** [comment]
Will merge the PR if there is no more comment.

**Review by jiwq — APPROVED** [review]
+1 Thanks @kobe860219 for the contribution and @lowc1012 for the review.

**Pull request closed without merging**
