### PR TITLE
SUBMARINE-587. [WEB]The list of notebook instances

### PR DESCRIPTION
**Pull request by kobe860219**
### What is this PR for?
Update notebook page of workbench to list all of the notebook instances in the given namespace.
First screenshot is show the page that list notebook by namespaces.
Second screenshot is the Restful result of `/v1/notebook`
The .gif  use mock data to test and show this feature.

And I fix error name of environment file.

### What type of PR is it?
[Feature]

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-587

### How should this be tested?
https://travis-ci.org/github/kobe860219/submarine/builds/720220622

### Screenshots (if appropriate)
截圖 2020-08-21 下午3 58 47
截圖 2020-08-22 下午11 21 19

螢幕錄製 2020-08-21 下午3

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by kobe860219** [comment]
@pingsutw  @lowc1012  @liuxunorg  @jiwq  Here I implement fronted page of notebook. List notebooks by different namespaces. Please help me review this pr. Thanks :) If need to show more details about notebook in table, let me know and I will add it.

**Comment by jiwq** [comment]
+1 Thanks @kobe860219 for the contribution. I think we should have an API to get the namespace for current user.

**Review by jiwq — APPROVED** [review]
+1 Thanks @kobe860219 for the contribution. I think we should have an API to get the namespace for current user.

**Review by pingsutw — COMMENTED** [review]
Thanks @kobe860219. It looks good to me.

**Pull request closed without merging**
