### PR TITLE
SUBMARINE-342. Upgrade Docker to use Ubuntu 18+

### PR DESCRIPTION
**Pull request by cchung100m**
### What is this PR for?
Examine and upgrade all Dockefile to use a Ubuntu 18+ image for the newer version of TensorFlow (1.14+), it was built with glibc 2.25+ and no longer compatible with Ubuntu 16 images.

### What type of PR is it?
Improvement

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-342

### How should this be tested?
https://travis-ci.com/cchung100m/submarine/builds/145045790
### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by liuxunorg** [comment]
hi @cchung100m thank you improving the submarine. 
I have 2 questions:
1. The title of PR is too long, I think it would be better to change to `Upgrade Docker to user Ubuntu 18+`
2. Because the submarine integrated travis has not yet checked docker, this part of your modification still relies on manual inspection. Can you provide the modified execution effect of each dockerfile? It can be a screenshot of the system operation. If the results are difficult to show, please explain.

Thanks again for your contribution!  
:-)

**Comment by cchung100m** [comment]
Hi @liuxunorg 

Thanks for the review, I would add the screenshots of the modified execution effect of each dockerfile, later.

**Comment by oliverhu** [comment]
+1 to @liuxunorg . @tangzhankun would you please provide some guidance for @cchung100m to validate?

**Comment by tangzhankun** [comment]
@cchung100m Thanks for the patch! It looks good to me. The basic test steps can be done through the mini-submarine.
1. Change the TensorFlow version here: https://github.com/apache/submarine/blob/master/dev-support/mini-submarine/submarine/build_python_virtual_env.sh#L23
2. Build the mini-submarine locally and run the minist example following this doc:
https://github.com/apache/submarine/tree/master/dev-support/mini-submarine

**Comment by jojochuang** [comment]
Just a nit: please change the commit message from "to user Ubuntu" to "to use Ubuntu" upon merge.

**Comment by liuxunorg** [comment]
> Just a nit: please change the commit message from "to user Ubuntu" to "to use Ubuntu" upon merge.
@cchung100m I help you change PR title.

**Comment by cchung100m** [comment]
Hi @liuxunorg @jojochuang @tangzhankun 

Thanks for the review and suggestions. I have changed the TensorFlow version, built the mini-submarine locally and run the minist example. Please refer the screenshot and log as below:

log: https://gist.github.com/cchung100m/f668d78486728c7eba988fe02fa4eb05

螢幕快照 2020-01-23 下午7 28 21

**Comment by liuxunorg** [comment]
@cchung100m Thank you contribution.
Will merge if no more comments.

**Comment by cchung100m** [comment]
Hi @liuxunorg 

Thanks for managing this PR. :)

**Pull request closed without merging**
