### PR TITLE
SUBMARINE-607. [WEB] Create and Delete of notebook instances

### PR DESCRIPTION
**Pull request by kobe860219**
### What is this PR for?
Make WEB UI support create/delete notebook instances.

### What type of PR is it?
[ Feature]

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-607

### How should this be tested?
https://travis-ci.org/github/kobe860219/submarine/builds/724836645

### Screenshots (if appropriate)
螢幕錄製 2020-09-07 下午4

螢幕錄製 2020-09-10 下午3

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by kobe860219** [comment]
@lowc1012 @pingsutw @jiwq @liuxunorg  Please help review this pr. Thanks :)

**Review by pingsutw — COMMENTED** [review]
Thanks @kobe860219 for the great effort
I think we could set the default GPU number to "0"
and maybe we could merge the two-stage pages into one.

**Review by pingsutw — APPROVED** [review]
+1, Thanks @kobe860219

**Review by lowc1012 — COMMENTED** [review]
@kobe860219  Thanks for your contribution.
This PR looks good to me.

**Review by xunliu — APPROVED** [review]
LGTM

**Pull request closed without merging**
