### PR TITLE
SUBMARINE-553. Modify "set -e" command in some shell scripts

### PR DESCRIPTION
**Pull request by lowc1012**
### What is this PR for?
The command "set -e" is not recommended in shell scripts.
It would be better to be replaced with "set -euo pipefail" 

### What type of PR is it?
[Bug Fix]

### What is the Jira issue?
[SUBMARINE-553](https://issues.apache.org/jira/projects/SUBMARINE/issues/SUBMARINE-553)

### How should this be tested?
[Travis CI](https://travis-ci.org/github/lowc1012/submarine/builds/704650038)

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by lowc1012** [comment]
@jiwq Thanks for your review! I will check these.

**Comment by lowc1012** [comment]
@pingsutw
Thanks for your reviews. I will keep set -x in those scripts,
and I found some bugs needed to fix.
WIP.

**Comment by lowc1012** [comment]
Hi, @jiwq @liuxunorg @pingsutw 
I pushed a fixed-commit. Could you help me for reviewing it again?
Thank you!

**Comment by pingsutw** [comment]
+1, Thanks @lowc1012

**Comment by liuxunorg** [comment]
Will merge if no more comments.

**Pull request closed without merging**
