### PR TITLE
Preparing for 0.6.0 development

### PR DESCRIPTION
**Pull request by pingsutw**
### What is this PR for?
Preparing for 0.6.0 development

### What type of PR is it?
[Release]

### Todos
* [ ] - Task

### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/SUBMARINE/
* Put link here, and add [SUBMARINE-*Jira number*] in PR title, eg. `SUBMARINE-23. PR title`

### How should this be tested?
* First time? Setup Travis CI as described on https://submarine.apache.org/contribution/contributions.html#continuous-integration
* Strongly recommended: add automated unit tests for any new or changed behavior
* Outline any manual steps to test the PR here.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by tangzhankun** [comment]
@pingsutw Thanks for the contribution! One question, is it hard for us to update version information besides maven pom.xml?

**Comment by pingsutw** [comment]
When updating `pom.xml`, we could use`mvn versions:set -DgenerateBackupPoms=false -DnewVersion=X.(Y+1).Z-SNAPSHOT`, but we need to manual update other files, I can improve it in `0.6.0`

**Review by xunliu — APPROVED** [review]
@pingsutw thanks you for you job!

**Review by yaooqinn — APPROVED** [review]

**Review by jiwq — APPROVED** [review]
+1 Thanks @pingsutw for the contribution and @tangzhankun @xunliu @yaooqinn for the review.

**Pull request closed without merging**
