### PR TITLE
SUBMARINE-763. Support uploading a conda config in environment page

### PR DESCRIPTION
**Pull request by KUAN-HSUN-LI**
### What is this PR for?
Support uploading conda config file interface in environment page

### What type of PR is it?
[Feature]

### Todos
* [ ] - Support the URL to upload the file.
* [ ] - Improve preview appearance.

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-763

### Screenshots (if appropriate)
ezgif com-gif-maker

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Review by pingsutw — COMMENTED** [review]
+1, thanks @KUAN-HSUN-LI 
@kobe860219 could you also take a look?

**Comment by kobe860219** [comment]
@KUAN-HSUN-LI @pingsutw Maybe we can move the upload and preview area to the next page?

**Comment by KUAN-HSUN-LI** [comment]
@pingsutw @kobe860219 The "Kernel Spec" which is below will be removed.
Or, maybe just put the preview inside the uploading area, and limit the height with a scroll bar.

**Comment by pingsutw** [comment]
@KUAN-HSUN-LI The current PR is okay with me.  
No need to change. Thanks.

**Pull request closed without merging**
