### PR TITLE
SUBMARINE-487. JNA does not work with maven-shade-plugin

### PR DESCRIPTION
**Pull request by gumartinm**
### What is this PR for?
submarine-spark-security fails with java.lang.UnsatisfiedLinkError

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-487

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by liuxunorg** [comment]
@gumartinm Thank you for your interest in the submarine project. :-)
@yaooqinn Please help review this PR, Thanks!

**Comment by yaooqinn** [comment]
Thanks for the fix, LGTM

**Comment by yaooqinn** [comment]
@gumartinm feel free to send follow-ups with your no-uber-jar ideas, I use uber-jar here because of jar conflict between spark and ranger project.

@liuxunorg I am ok to merge this.

**Comment by gumartinm** [comment]
> @gumartinm feel free to send follow-ups with your no-uber-jar ideas, I use uber-jar here because of jar conflict between spark and ranger project.
> 
> @liuxunorg I am ok to merge this.

@yaooqinn I just wanted to say that you are doing a great job with this project. I've been following it since it was called [spark-authorizer](https://github.com/yaooqinn/spark-authorizer ). Hopefully, one day, it will be integrated in the Spark framework.

**Pull request closed without merging**
