### PR TITLE
SUBMARINE-653. Replace workbench-web-ng with workbench-web

### PR DESCRIPTION
**Pull request by kevin85421**
### What is this PR for?
In SUBMARINE-640, we remove the outdated workbench (vue). Therefore, we can replace workbench-web-ng with workbench-web. 

### What type of PR is it?
[Improvement]

### Todos
Update documents related to workbench

### What is the Jira issue?
https://issues.apache.org/jira/projects/SUBMARINE/issues/SUBMARINE-653?filter=allopenissues

### How should this be tested?
https://travis-ci.org/github/kevin85421/hadoop-submarine/builds/732898467

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by xunliu** [comment]
@kevin85421 Please fix branch conflicts.

**Review by xunliu — COMMENTED** [review]
@kevin85421 Please fix branch conflicts.

**Comment by kevin85421** [comment]
@xunliu Thanks! I have rebased it.

**Comment by kevin85421** [comment]
@xunliu Thanks! I have rebased it.

**Comment by pingsutw** [comment]
+1, will commit if no more comment.

**Review by pingsutw — APPROVED** [review]
+1, will commit if no more comment.

**Pull request closed without merging**
