### PR TITLE
SUBMARINE-269. Update Docs After Spin-off

### PR DESCRIPTION
**Pull request by wangdatan**
### What is this PR for?
Update docs after spin-off

### What type of PR is it?
Documentation

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-269

### How should this be tested?
* First time? Setup Travis CI as described on https://submarine.apache.org/contribution/contributions.html#continuous-integration
* Strongly recommended: add automated unit tests for any new or changed behavior
* Outline any manual steps to test the PR here.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? N/A

### CODE REVIEW

**Comment by wangdatan** [comment]
One TODO item: https://github.com/apache/submarine/blob/wangdatan-patch-1/docs/community/contributing.md has lots of scripts, it's better to let either @liuxunorg , @yuanzac to update that doc.

**Comment by wangdatan** [comment]
And I made a mistake that creating a submarine branch instead of my own fork, will fix it next time.

**Comment by leftnoteasy** [comment]
@liuxunorg , @yuanzac , @tangzhankun can you help to check this?

**Comment by wangdatan** [comment]
Close and creating a new one.

**Pull request closed without merging**
