### PR TITLE
SUBMARINE-635. [WEB] Add sync code to experiment UI

### PR DESCRIPTION
**Pull request by kobe860219**
### What is this PR for?
Before pod starting, need to clone git-repo to /code/current.
And disable some routerlink to WIP page.

### What type of PR is it?
[Feature]

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-635

### How should this be tested?
https://travis-ci.org/github/kobe860219/submarine/builds/730755150

### Screenshots (if appropriate)
螢幕錄製 2020-09-28 下午1

120136838_966648427146981_8787822419064498915_n

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by kobe860219** [comment]
@pingsutw @xunliu  Please help me review this pr. Thanks !

**Comment by pingsutw** [comment]
Screenshot from 2020-09-28 13-02-37
Thanks @kobe860219 for the contribution
- Could you take a look at test failure
- And I think it's better to put `environment` input and button under `git repository`

**Review by pingsutw — APPROVED** [review]
LGTM, thanks

**Review by xunliu — APPROVED** [review]
LGTM
Will merge if no more comments.

**Pull request closed without merging**
