### PR TITLE
SUBMARINE-791. Read Submaine CRD spec in controller

### PR DESCRIPTION
**Pull request by MortalHappiness**
### What is this PR for?
After defining the spec for Submarine CRD, we need to read the spec in our controller.

### What type of PR is it?
[Feature]

### Todos
* [x] - Modify types.go to meet the CRD spec.
* [x] - Modify controller.go such that it can read the CRD spec.

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-791

### How should this be tested?
https://travis-ci.org/github/MortalHappiness/submarine/builds/766867816

### Screenshots (if appropriate)
SUBMARINE-791

### Questions:
* Do the license files need updating? No
* Are there breaking changes for older versions? No
* Does this need new documentation? No

### CODE REVIEW

**Review by kevin85421 — COMMENTED** [review]
Thank @MortalHappiness for your contribution!

It looks good to me. Can you run it in-cluster?

**Comment by MortalHappiness** [comment]
The following image shows that the controller can run in the cluster. Thanks.

image

**Review by kevin85421 — APPROVED** [review]
LGTM

**Review by xunliu — APPROVED** [review]
LGTM
Will merge if no more comments.

**Comment by xunliu** [comment]
@MortalHappiness did you complated this pr? I see you force pushed again.

**Comment by MortalHappiness** [comment]
@xunliu Yes, I’ve completed this PR. Thanks.

**Comment by MortalHappiness** [comment]
I rebased again just now to sync with the master branch.

**Pull request merged**
