### PR TITLE
SUBMARINE-461. [WEB] Implement department page with Angular

### PR DESCRIPTION
**Pull request by jasoonn**
### What is this PR for?
Implement frontend of department page in workbench with Angular.

### What type of PR is it?
[Feature]

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-461

### How should this be tested?
https://travis-ci.org/github/apache/submarine/builds/673989361

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by jasoonn** [comment]
@liuxunorg @kobe860219 Can you help me review the pull request? Thanks!

**Comment by liuxunorg** [comment]
@jasoonn Thank you for contribution this feature.
Will merge if no more comments.

**Comment by kobe860219** [comment]
@jasoonn Thank you for contribution this feature. It is looks good to me.
Is it need to add  blank line at the end of the file?

**Comment by jasoonn** [comment]
@kobe860219 Thank you for the advice. I have added blank line at the end of the file, but it doesn't show here. Furthermore, I think it is ok, because there would appear "missing of end of line" in file changes part, if I didn't add blank line.

**Pull request closed without merging**
