### PR TITLE
SUBMARINE-850. Add operator e2e test framework

### PR DESCRIPTION
**Pull request by Kenchu123**
### What is this PR for?

Setup operator e2e test framework for further test case
Reference: [spark-on-k8s-operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/master/test/e2e)

This PR will test the following:
- Create submarine-operator
- Delete submarine-operator

### What type of PR is it?

Feature

### Todos

* [ ] Operator state maintain

Test case:
* [ ] Create submarine
* [ ] Delete submarine
* [ ] Scale submarine

### What is the Jira issue?

https://issues.apache.org/jira/browse/SUBMARINE-850

### How should this be tested?

```bash
# Step1: Build image "submarine-operator" to minikube's Docker 
eval $(minikube docker-env)
make image

# Step2: Register Custom Resource Definition
kubectl apply -f artifacts/examples/crd.yaml

# Step3: Run test
go test ./test/e2e
```

### Screenshots (if appropriate)

https://user-images.githubusercontent.com/17617373/121552095-c2377a00-ca42-11eb-967e-263e6a7734a9.mov

### Questions:
* Do the license files need updating? No
* Are there breaking changes for older versions? No
* Does this need new documentation? No

### CODE REVIEW

**Review by xunliu — COMMENTED** [review]
@Kenchu123 
What content has been tested in this E2E?
 please list it so that everyone can understand more easily.

**Comment by kevin85421** [comment]
@xunliu This PR is a test framework for Submarine operator. To elaborate, it implements hooks which are similar to `@BeforeClass` and `@AfterClass` in JUnit. In addition, this PR still needs to be updated due to the modification in SUBMARINE-848 ([PR](https://github.com/apache/submarine/pull/606)).

**Comment by Kenchu123** [comment]
> @xunliu This PR is a test framework for Submarine operator. To elaborate, it implements hooks which are similar to `@BeforeClass` and `@AfterClass` in JUnit. In addition, this PR still needs to be updated due to the modification in [SUBMARINE-848](https://issues.apache.org/jira/browse/SUBMARINE-848) ([PR](https://github.com/apache/submarine/pull/606)).

**Comment by Kenchu123** [comment]
@kevin85421  I have fixed the namespace for [SUBMARINE-848](https://issues.apache.org/jira/browse/SUBMARINE-848) ([PR](https://github.com/apache/submarine/pull/606)). Besides, I have edited the PR details, and added more helper functions in framework for further test case.

**Comment by Kenchu123** [comment]
@kevin85421  I have made change for [SUBMARINE-889](https://issues.apache.org/jira/browse/SUBMARINE-889)([PR](https://github.com/apache/submarine/commit/10a41504022c6158c19cbaf5d1292835806ed2e2))

**Review by kevin85421 — APPROVED** [review]
LGTM

**Pull request closed without merging**
