### PR TITLE
Submarine-368. [WEB] Add items to the sidebar with Angular

### PR DESCRIPTION
**Pull request by kevin85421**
### What is this PR for?
1. The attachment is the sidebar of the version Vue. Our target is implementing a similar sidebar with Angular.
截圖 2020-01-31 下午3 01 00
2. Add E2E unit test cases of the navigation of the sidebar.
3. Update the E2E test framework to avoid some compilation errors.
### What type of PR is it?
Feature

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-368

### How should this be tested?
https://travis-ci.org/apache/submarine/builds/645786845?utm_source=github_status&utm_medium=notification

### Screenshots (if appropriate)
截圖 2020-02-03 下午10 46 39

### Questions:
* Does the licenses files need an update? No
* Are there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by kevin85421** [comment]
@yuanzac I modified the file FirefoxWebDriverProvider.java. To elaborate, I change the value of **DRIVER_USE_MARIONETTE** from **false** to **true**. Without the modification, I cannot compile the code successfully. In addition, my OS is macOS 10.15.2. Can you help me review the file FirefoxWebDriverProvider.java? Thanks!

**Comment by yuanzac** [comment]
Thanks, @kevin85421.
For now, chrome is used for the e2e test. You can check code line 46 - 53 of WebDriverManager.  Besides, the travis log shows that chrome is used. If chrome failed, we will try firefox. But firefox doesn't work actually. If you have bindwidth, you can help figure out how to use firefox in travis.

You mean the value of DRIVER_USE_MARIONETTE blocks your compilations? I'm not sure about that.

**Comment by kevin85421** [comment]
Thanks, @yuanzac.
I execute the E2E test on my localhost (not on travis). On my Macbook Pro, I cannot execute the test with Chrome driver, and hence I used Firefox driver. I can try to figure out how to use Firefox driver on travis in the future. Thanks!

**Comment by liuxunorg** [comment]
@kevin85421  Thank you contribution.
E2E testing is very important to us, and it is worth taking some time to do it well.

**Comment by kevin85421** [comment]
Thanks, @yuanzac and @liuxunorg 
I have reported the issue of E2E test framework [SUBMARINE-374](https://issues.apache.org/jira/projects/SUBMARINE/issues/SUBMARINE-374).

**Pull request closed without merging**
