### PR TITLE
SUBMARINE-957. Extract helm dependencies from submarine operator

### PR DESCRIPTION
**Pull request by MortalHappiness**
### What is this PR for?
Instead of installing helm dependencies in our operator, we should install these dependencies using helm CLI from outside. In this way, we do not need to maintain helm dependencies in our operator. This can help us develop the multi-tenant feature.

### What type of PR is it?
[Improvement]

### What is the Jira issue?
https://issues.apache.org/jira/projects/SUBMARINE/issues/SUBMARINE-957

### Questions:
* Do the license files need updating? No
* Are there breaking changes for older versions? No
* Does this need new documentation? No

### CODE REVIEW

**Comment by kevin85421** [comment]
@Kenchu123 can you review this PR? Thanks!

**Comment by Kenchu123** [comment]
I have found out that the traefik service was `submarine-operator-traefik`, this may be the `fullName` setting in `charts/traefik/templates/_helpers.tpl`.

Maybe you should replace the `service/submarine-traefik` to `service/submarine-operator-traefik` in the `kubectl portfoword` in README?

image

**Comment by MortalHappiness** [comment]
@Kenchu123 I have updated the README. Thank you.

**Comment by Kenchu123** [comment]
@kevin85421  @MortalHappiness  LGTM.

**Review by kevin85421 — APPROVED** [review]

**Pull request closed without merging**
