### PR TITLE
SUBMARINE-879. Experiment logs have not displayed

### PR DESCRIPTION
**Pull request by aeioulisa**
### What is this PR for?
Fix the bug of experiment logs in the workbench have not displayed.

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/projects/SUBMARINE/issues/SUBMARINE-879

### Questions:
* Do the license files need updating? Yes/No
* Are there breaking changes for older versions? Yes/No
* Does this need new documentation? Yes/No

### CODE REVIEW

**Comment by ByronHsu** [comment]
@jiwq Can you help review this PR?
I think that [this line](submarine-server/server-core/src/main/java/org/apache/submarine/server/experiment/ExperimentManager.java) should also be replaced with `submitter.getExperimentLog`. I am not sure the purpose of `getExperimentLogName`. Thanks!

**Review by cxorm — APPROVED** [review]
+1, thanks for fixing it.

**Review by jiwq — APPROVED** [review]
+1 After the conflicting file resolved.

**Comment by ByronHsu** [comment]
@jiwq Should this line also be changed? https://github.com/apache/submarine/blob/2fac4f874bf2b1308fa6b7299a00888cc318708d/submarine-server/server-core/src/main/java/org/apache/submarine/server/experiment/ExperimentManager.java#L261

**Comment by jiwq** [comment]
> @jiwq Should this line also be changed?
> 
> https://github.com/apache/submarine/blob/2fac4f874bf2b1308fa6b7299a00888cc318708d/submarine-server/server-core/src/main/java/org/apache/submarine/server/experiment/ExperimentManager.java#L261

Yes. Thank you for your careful review. @ByronHsu

**Comment by ByronHsu** [comment]
@jiwq What is the purpose of logName? Do we need to keep it or we just need log?

**Comment by jiwq** [comment]
> @jiwq What is the purpose of logName? Do we need to keep it or we just need log?

Sorry, I don't remember the purpose. I checked the code and think we can use `getExperimentLog`.

**Comment by aeioulisa** [comment]
Thank @ByronHsu, @jiwq and @cxorm for the reviews.
I think the method "listExperimentLogsByStatus" just list the log names and "getExperimentLog" is to get the logs. 
Feel free to correct me if I miss something.

**Review by pingsutw — APPROVED** [review]
LGTM

**Pull request closed without merging**
