### PR TITLE
SUBMARINE-522. [WEB] Improve experiment information page

### PR DESCRIPTION
**Pull request by kobe860219**
### What is this PR for?
1. Pre-add column of duration. (Future work)
2. Support pod select, and improve log page.

### What type of PR is it?
[ Feature]

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-522

### How should this be tested?
https://travis-ci.org/github/kobe860219/submarine

### Screenshots (if appropriate)
螢幕快照 2020-06-29 下午8 05 56
螢幕快照 2020-06-29 下午8 05 43
螢幕快照 2020-06-29 下午8 05 31

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by kobe860219** [comment]
@pingsutw  @liuxunorg  @jasoonn  @chiajoukuo Please help me review this pr, thanks!

**Comment by jasoonn** [comment]
@kobe860219 Thank for your contribution. It looks good to me.

**Comment by chiajoukuo** [comment]
@kobe860219  Thank you for your contribution. It looks good to me.

**Comment by kobe860219** [comment]
@pingsutw  I have updated screenshots.

**Comment by kobe860219** [comment]
@liuxunorg Thanks. I have updated title.

**Comment by pingsutw** [comment]
Thanks @kobe860219 
+1

**Pull request closed without merging**
