### PR TITLE
SUBMARINE-700. [WEB] Refactor notebook page of Workbench

### PR DESCRIPTION
**Pull request by kobe860219**
### What is this PR for?
Refactor the architecture of notebook component in workbench. The new architecture is as below :

Notebook Architecture

### What type of PR is it?
[Refactoring]

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-700

### How should this be tested?
https://travis-ci.org/github/kobe860219/submarine/builds/755191807

### Screenshots (if appropriate)
notebook page demo 20210127

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by ByronHsu** [comment]
Thanks for your contribution! I have some suggestions. The form style now is not consistent with the experiment page (in the experiment, the form is floated above the list as we click "create experiment"). I think that form and list should be at the same routing path, just like what we do on the experiment page.

**Comment by kobe860219** [comment]
@ByronHsu  Thanks your review and suggestions. I will refactor page's style and component's routing with an unified architecture as soon as possible. Thanks a lot !

**Comment by kobe860219** [comment]
@ByronHsu Hi, I have readjusted the notebook form as the style in experiment page.
@pingsutw [SUBMARINE-716](https://issues.apache.org/jira/browse/SUBMARINE-716) I modified in this PR.

**Review by xunliu — COMMENTED** [review]
@kobe860219 good job!
I think that when deleting a notebook, there needs to be a confirmation dialog box to prevent users from misoperation.

**Comment by kobe860219** [comment]
@xunliu  Thanks your review, I added confirmation dialog box in latest commit.

**Comment by kobe860219** [comment]
@ByronHsu Thanks your review. In the previous PR, I referred to kubeflow's approach. Indeed, the polling method seems too complicated, so I simplified it.

**Comment by ByronHsu** [comment]
LGTM

**Comment by pingsutw** [comment]
Could you also help me update the image in https://github.com/apache/submarine/blob/master/docs/userdocs/k8s/notebook.md
Screenshot from 2021-01-29 04-35-17

**Review by pingsutw — CHANGES_REQUESTED** [review]
@kobe860219 Thanks for your contribution.
Could you fix the test failure? It seems that the failures are related to this PR.
btw, Could you also help me update the image in https://github.com/apache/submarine/blob/master/docs/userdocs/k8s/notebook.md
Screenshot from 2021-01-29 04-35-17

**Comment by kobe860219** [comment]
@pingsutw  I will fix test failure and update doc's image !

**Review by pingsutw — APPROVED** [review]
LGTM, Thanks @kobe860219

**Pull request closed without merging**
