### PR TITLE
SUBMARINE-697. Provide an environment whose image includes CUDA

### PR DESCRIPTION
**Pull request by charlie0220**
### What is this PR for?
Add an notebook environment  which include CUDA v10.2

### What type of PR is it?
[Improvement]

### Todos
* [ ] - Task

### What is the Jira issue?
[SUBMARINE-697](https://issues.apache.org/jira/projects/SUBMARINE/issues/SUBMARINE-697?filter=myopenissues)

### How should this be tested?
[Travic CI](https://travis-ci.org/github/charlie0220/submarine/builds/764863993)

### Screenshots (if appropriate)
cuda-env

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Review by pingsutw — COMMENTED** [review]
@charlie0220 Thanks for the contribution.
I suggest that changing the name `notebook-cuda` and `jupyter-cuda` to `notebook-gpu` and `jupyter-gpu`
btw, did you successfully run an experiment using this image?

**Comment by xunliu** [comment]
@charlie0220 What status for this PR?
In addition, Please trigger travis CI again, I see it failed.

**Review by xunliu — COMMENTED** [review]
@charlie0220 What status for this PR?
In addition, Please trigger travis CI again, I see it failed.

**Comment by jojochuang** [comment]
Re-triggered the build: https://travis-ci.com/github/apache/submarine/jobs/496929793

**Comment by charlie0220** [comment]
I have successfully run the experiment using this image and now I'm working on solving travis's problem.

**Review by xunliu — COMMENTED** [review]
Will merge if no more comments.

**Pull request closed without merging**
