### PR TITLE
SUBMARINE-937. [Dev] Update test-e2e doc

### PR DESCRIPTION
**Pull request by noidname01**
### What is this PR for?

Update the doc of the test-e2e.

### What type of PR is it?
[ Documentation ]

### Todos

None

### What is the Jira issue?

https://issues.apache.org/jira/projects/SUBMARINE/issues/SUBMARINE-937

### How should this be tested?

None

### Screenshots (if appropriate)

None

### Questions:
* Do the license files need updating? No
* Are there breaking changes for older versions? No
* Does this need new documentation? No

### CODE REVIEW

**Review by kevin85421 — APPROVED** [review]
LGTM

**Comment by noidname01** [comment]
> @noidname01 There is a conflicting file.

Oh, I'll fix it ASAP.

**Comment by noidname01** [comment]
Fixed!

**Comment by kevin85421** [comment]
@noidname01 There is a conflicting file.

**Comment by noidname01** [comment]
> @noidname01 There is a conflicting file.

Fixed it again!

**Comment by kevin85421** [comment]
LGTM

**Pull request closed without merging**
