### PR TITLE
SUBMARINE-527. [SDK] Abstract client API

### PR DESCRIPTION
**Pull request by pingsutw**
### What is this PR for?
Try to simplify client API that generated by swagger, we could add an abstract layer on swagger API, and let users more easily submit experiments
Also, prettify output in the notebook

Before:  [Jupyter example](https://github.com/pingsutw/hadoop-submarine/blob/SUBMARINE-516/submarine-sdk/pysubmarine/example/submarine_experiment_sdk.ipynb) 
After: [Jupyter example](https://github.com/pingsutw/hadoop-submarine/blob/SUBMARINE-527/submarine-sdk/pysubmarine/example/submarine_experiment_sdk.ipynb)

### What type of PR is it?
[Improvement]

### Todos
* [ ] - e2e test
* [ ] - unit test

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-527?jql=project%20%3D%20SUBMARINE#

### How should this be tested?
https://travis-ci.org/github/pingsutw/hadoop-submarine/builds/699648185

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by pingsutw** [comment]
I found that `list_log` only output **podName**, and **podLog** always is NULL.
Should we change to `list_podsName`?
https://github.com/apache/submarine/blob/0f281cad18ed5c1549b1286a9358a1eceba5991e/submarine-server/server-core/src/main/java/org/apache/submarine/server/rest/ExperimentRestApi.java#L180-L195
http://submarine:8080/api/v1/experiment/logs
output:
```json
{
  "status": "OK",
  "code": 200,
  "success": true,
  "message": null,
  "result": [
    {
      "experimentId": "experiment_1592474530204_0001",
      "logContent": [
        {
          "podName": "tf-mnist-json-ps-0",
          "podLog": []
        },
        {
          "podName": "tf-mnist-json-worker-0",
          "podLog": []
        }
      ]
    }
  ],
  "attributes": {}
}
```
/cc @jiwq @tangzhankun

**Comment by tangzhankun** [comment]
@pingsutw Thanks for the update! The "list experiment log by status" might have bugs in it? Need confirmation from @jiwq 

For the API, can we add a wait_for_finish(id) method which gets logs periodically until the experiment finish?

**Comment by pingsutw** [comment]
@tangzhankun I've add `wait_for_finish`

**Comment by tangzhankun** [comment]
@pingsutw , thanks for the update! LGTM. Does the Travis failure relate to the PR?

**Comment by pingsutw** [comment]
it's unrelated to the PR, I've moved all testing to GitHub-action

**Comment by tangzhankun** [comment]
@pingsutw Thanks for the contribution. Committed.

**Pull request closed without merging**
