### PR TITLE
SUBMARINE-784. Grammar fixes

### PR DESCRIPTION
**Pull request by fredster33**
### What is this PR for?
A few minor grammar fixes for the README and pull request template.

### What type of PR is it?
Documentation

### Todos
None

### What is the Jira issue?
https://issues.apache.org/jira/projects/SUBMARINE/issues/SUBMARINE-784

### How should this be tested?
No tests applicable.

### Screenshots (if appropriate)
N/A

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Review by xunliu — APPROVED** [review]
@fredster33 Thank you fixed this typo. :-)
Please submit your changes in accordance with our specifications. http://submarine.apache.org/docs/community/contributing

**Comment by pingsutw** [comment]
@fredster33 could you create a JIRA ticket in the https://issues.apache.org/jira/projects/SUBMARINE/issues/SUBMARINE ?

**Comment by fredster33** [comment]
> @fredster33 could you create a JIRA ticket in the https://issues.apache.org/jira/projects/SUBMARINE/issues/SUBMARINE ?

Will do, okay.

**Comment by fredster33** [comment]
Got it, it is available at https://issues.apache.org/jira/projects/SUBMARINE/issues/SUBMARINE-784.

**Review by xunliu — APPROVED** [review]
Will merge if no more comments.

**Comment by xunliu** [comment]
@fredster33 Thank you for your contribution.
I have set up JIRA permission for you, next time, you can create jira and assign it to youself.

**Pull request closed without merging**
