### PR TITLE
SUBMARINE-431. [WEB] Implement data page with Angular

### PR DESCRIPTION
**Pull request by jasoonn**
### What is this PR for?
Implement frontend of data page in workbench with Angular

### What type of PR is it?
 Feature 

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-431

### How should this be tested?
[Travis](https://github.com/apache/submarine/pull/244/checks)

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by jasoonn** [comment]
@kevin85421 @liuxunorg Can you help me review the pull request? Thanks!

**Comment by liuxunorg** [comment]
@jasoonn Thank you for contribution this feature.
PR title format like this : `SUBMARINE-431. pr title ......`

**Comment by liuxunorg** [comment]
@kevin85421 please help review this PR, Thanks.

**Comment by jasoonn** [comment]
@liuxunorg Thank for your advice!

**Pull request closed without merging**
