### PR TITLE
SUBMARINE-625. [WEB] Support running standalone script

### PR DESCRIPTION
**Pull request by pingsutw**
### What is this PR for?
Support running any python script in a single node.

### What type of PR is it?
[Feature]

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-625

### How should this be tested?
https://travis-ci.org/github/pingsutw/hadoop-submarine/builds/727226256

### Screenshots (if appropriate)
Screenshot from 2020-09-15 09-30-11
Screenshot from 2020-09-18 17-51-01
Screenshot from 2020-09-18 17-51-18
Screenshot from 2020-09-18 17-51-24
Screenshot from 2020-09-18 17-51-32

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Review by xunliu — COMMENTED** [review]
@pingsutw Please add `SUBMARINE-625.` to PR title.

**Review by jiwq — APPROVED** [review]
LGTM Thanks @pingsutw for the work. Will commit if no more comments after 2 business days.

**Comment by pingsutw** [comment]
@xunliu @jiwq Thanks for the review.
After discuss in online meeting, I will revise the UI again. 
Please don't merge this PR.

**Comment by jiwq** [comment]
> @xunliu @jiwq Thanks for the review.
> After discuss in online meeting, I will revise the UI again.
> Please don't merge this PR.

👌, I think you could better convert it to draft until it can be merged.

**Comment by pingsutw** [comment]
Ready for review. Update includes
- Decrease description input size
- Increase command input size
- Combine `meta` and `env` page to single page 
- Add a dropdown window to select namespace and image
- Add a preview page
- Add advanced button, click advanced button if need to update `namespace` and `environment variable`

**Comment by jiwq** [comment]
+1 Will commit if no more comments.

**Pull request closed without merging**
