### PR TITLE
SUBMARINE-754. Add Experiment Auto Reload

### PR DESCRIPTION
**Pull request by noidname01**
### What is this PR for?

Add Experiment Auto Reload

### What type of PR is it?

[Improvement]

### What is the Jira issue?

https://issues.apache.org/jira/browse/SUBMARINE-754

### Screenshots (if appropriate)

Peek 2021-03-03 18-00

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by kevin85421** [comment]
@noidname01  Thank you for your contribution! I have some recommendations for your pull request title.

The pull request title must follow the following format:

SUBMARINE-${jira_number}. ${jira_summary}

e.g.

SUBMARINE-754. Add Experiment Auto Reload
(SUBMARINE must be upper case)

With the correct pull request title, JIRA can link this pull request automatically.

**Comment by ByronHsu** [comment]
@noidname01 Can you add a demo gif?

**Comment by noidname01** [comment]
@ByronHsu Thanks for noticing me, I'll attach it later.

**Comment by ByronHsu** [comment]
A little suggestion.

**Comment by ByronHsu** [comment]
@noidname01 I have tested it on my local side, and it works pretty fine! Thanks for your contribution.

**Review by xunliu — COMMENTED** [review]
@noidname01 Thank you for contribution.
Please attach snapshot gif in Screenshots (if appropriate) paragraph, don't put git url address.

**Comment by noidname01** [comment]
Gif has been attached.

**Review by pingsutw — APPROVED** [review]
+1

**Pull request closed without merging**
