### PR TITLE
SUBMARINE-1028. Extend timeout for integration tests

### PR DESCRIPTION
**Pull request by KUAN-HSUN-LI**
### What is this PR for?
Sometimes GitHub Actions' server is not stable, then it will take around 20 minutes and lead to timeout of integration tests.

### What type of PR is it?
[Improvement]

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-1028

### Questions:
* Do the license files need updating? No
* Are there breaking changes for older versions? No
* Does this need new documentation? No

### CODE REVIEW

**Review by pingsutw — APPROVED** [review]
+1, Thanks for fixing it.

**Comment by cxorm** [comment]
Overall LGTM, just one question from my side.

Could you please share the reason that setting the new timeout-minutes to 60 instead of other time ?

**Comment by KUAN-HSUN-LI** [comment]
@cxorm If there isn't a restart happen, test-k8s needs around 14 minutes, and test-e2e needs around 9 minutes. Usually restart will take 20~30 minutes therefore I think 60 minutes is a proper setting. Additionally, the integration test in python workflow is also using 60 minutes for the timeout.

**Review by cxorm — APPROVED** [review]
Nice catch, +1

**Pull request closed without merging**
