### PR TITLE
SUBMARINE-722. [WEB] Add template page on workbench

### PR DESCRIPTION
**Pull request by kobe860219**
### What is this PR for?
Complete template page on workbench. This pr is a UI for users to register new pre-defined experiment template. Now user could register a pre-defined experiment template, then run experiments quickly with different hyper-parameters.

### What type of PR is it?
[Feature]

### Todos
* [ ] - templateIT

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-722

### How should this be tested?
https://github.com/kobe860219/submarine/runs/2325676029

### Screenshots (if appropriate)
截圖 2021-04-13 上午12 18 14
截圖 2021-04-13 上午12 18 23
截圖 2021-04-13 上午12 18 38
截圖 2021-04-13 上午12 18 47
截圖 2021-04-13 上午12 19 03
截圖 2021-04-13 上午12 19 13

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Review by xunliu — COMMENTED** [review]
The description in PR is too simple.
What template? Job Template?

**Comment by kobe860219** [comment]
@xunliu  Sorry ! This pr is a UI for users to register new pre-defined experiment template. Now user could register a pre-defined experiment template, then run experiments quickly with different hyper-parameters.

**Comment by xunliu** [comment]
LGTM

**Review by xunliu — APPROVED** [review]
@kobe860219 Thank you for your contribution.
Will merge if no more comments.

**Pull request closed without merging**
