### PR TITLE
SUBMARINE-430. [WEB] Implement Interpreter page with Angular

### PR DESCRIPTION
**Pull request by kevin85421**
### What is this PR for?
Implement frontend of Interpreter page in workbench with Angular

### What type of PR is it?
[Feature]

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-430

### How should this be tested?
https://travis-ci.org/github/apache/submarine/builds/663381988?utm_source=github_status&utm_medium=notification

### Screenshots (if appropriate)
截圖 2020-03-17 下午3 12 12
截圖 2020-03-17 下午3 12 28
### Questions:
* Does the licenses files need an update? No
* Are there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by liuxunorg** [comment]
@kevin85421 Thank you for contribution.
Some check errors here have nothing to do with your PR. Just make sure Travis is correct.
Can you attach a screenshot of the PR?

**Comment by kevin85421** [comment]
> @kevin85421 Thank you for contribution.
> Some check errors here have nothing to do with your PR. Just make sure Travis is correct.
> Can you attach a screenshot of the PR?

@liuxunorg  Thank you for your recommendation. I have attached the screenshots to the pr. In addition, I will check Travis status.

**Comment by pingsutw** [comment]
@kevin85421 SDK failure is unrelated to it.
The test is flaky in python 3.5 
I have fixed in #230
Sorry about that.

**Comment by kevin85421** [comment]
@liuxunorg I have checked [the status of Travis](https://travis-ci.org/github/apache/submarine/builds/663381988?utm_source=github_status&utm_medium=notification), and it does not have any problem. 
@jasoonn Can you help me review the pull request? Thanks a lot.

**Comment by kevin85421** [comment]
> @kevin85421 SDK failure is unrelated to it.
> The test is flaky in python 3.5
> I have fixed in #230
> Sorry about that.

@pingsutw Thank you for your information. No worries : )

**Pull request closed without merging**
