### PR TITLE
SUBMARINE-802. Refactor environment list

### PR DESCRIPTION
**Pull request by KUAN-HSUN-LI**
### What is this PR for?
* Refactor the environment list.
* Add the preview environment spec button.
* Download button for environment spec.

### What type of PR is it?
[Refactoring]

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-802

### How should this be tested?
Test download case is created in e2e test.

### Screenshots (if appropriate)
ezgif com-gif-maker

### Questions:
* Do the license files need updating? No
* Are there breaking changes for older versions? No
* Does this need new documentation? No

### CODE REVIEW

**Comment by KUAN-HSUN-LI** [comment]
Bump the ng-zorro-antd from 8.1.2 to 8.5.2 since the popover component is broken in the old version.

**Comment by ByronHsu** [comment]
Thanks for your contribution! Will review later.

**Comment by ByronHsu** [comment]
@KUAN-HSUN-LI  The PR title should follow the format

**Review by xunliu — APPROVED** [review]
@KUAN-HSUN-LI Thank you for your contributions. 
LGTM
Will merge if no more comments.

**Pull request closed without merging**
