### PR TITLE
SUBMARINE-737. Fix router link in e2e test

### PR DESCRIPTION
**Pull request by kobe860219**
### What is this PR for?
SUBMARINE-729 fix the blank page after redirect, so should fix e2e test about testing router link.

### What type of PR is it?
[Bug Fix]

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-737

### How should this be tested?
https://travis-ci.org/github/kobe860219/submarine/builds/758805284

### Screenshots (if appropriate)
截圖 2021-02-13 下午4 17 52
截圖 2021-02-13 下午4 23 45

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by kobe860219** [comment]
@pingsutw This PR fix the problem in travis's tests which caused by SUBMARINE-729.

**Comment by pingsutw** [comment]
Hi @kobe860219. The Travis tests still fail, could you take a look?

**Comment by kobe860219** [comment]
@pingsutw In my travis, now e2e-test is success. Thanks !
image

**Review by pingsutw — APPROVED** [review]
+1, Great.
Thanks @kobe860219 for the contribution.

**Pull request closed without merging**
