### PR TITLE
SUBMARINE-789. Update the link of HitCount

### PR DESCRIPTION
**Pull request by aeioulisa**
### What is this PR for?
The link of HitCount doesn't work on README now and we would move the domain from .io to .com to fix it.

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-789

### Screenshots (if appropriate)
image

### Questions:
* Do the license files need updating? No
* Are there breaking changes for older versions? No
* Does this need new documentation? No

### CODE REVIEW

**Review by xunliu — COMMENTED** [review]
@aeioulisa Thanks you fixed this issue.

I found another probleam.
I see that `# What is Apache Submarine?` is not display correctly, 
It should show up as head style. Please help fix it. Thanks.

like this,
# What is Apache Submarine?

**Comment by aeioulisa** [comment]
@xunliu Thanks for your review.
I have fixed this problem.

**Review by lowc1012 — APPROVED** [review]
+1

**Review by xunliu — APPROVED** [review]
LGTM
Will merge if no more comments.

**Pull request closed without merging**
